version: '2'

networks:
  punisher:
    external: true

services:
  punisher-db:
    image: percona:5.7
    restart: always
    volumes:
      - ./configs/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - punisher

  punisher:
    image: hub.maddevs.co/punisher
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - PUNISH_TIME=${PUNISH_TIME}
      - INTERNS_CHAT_ID=${INTERNS_CHAT}
    networks:
      - punisher
